version: '3.8'

services:
  custom-postgres:
    hostname: postgres
    image: postgres
    container_name: edupo-app
    restart: always
    ports:
      - '5430:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=edupo_db
    networks:
      - my_network
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:

networks:
  my_network: